// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izvtsulcazrsnwwfzkrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6dnRzdWxjYXpyc253d2Z6a3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODkxMDUsImV4cCI6MjA1OTk2NTEwNX0.MMZVbe5u1sn3hzhAC3iq5vCL_1pvhgScG16DNZF40iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);